
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "table.sort(self.cards, function (a, b) return a.T.x + a.T.w/2 - 100*(a.pinned and a.sort_id or 0) < b.T.x + b.T.w/2 - 100*(b.pinned and b.sort_id or 0) end)"
position = "at"
payload = '''
table.sort(self.cards, function (a, b)
            local a_val = a.T.x + a.T.w/2 - 100*(a.pinned and a.sort_id or 0)
            local b_val = b.T.x + b.T.w/2 - 100*(b.pinned and b.sort_id or 0)

            if a.pinned_right and b.pinned_right then
                return a_val > b_val
            elseif a.pinned_right then
                return false
            elseif b.pinned_right then
                return true
            else
                return a_val < b_val
            end
        end)
'''
match_indent = true
overwrite = false